version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci(github)'
    labels: ['tech. enhancement']
    rebase-strategy: 'disabled'

  - package-ecosystem: 'npm'
    directory: '/'
    cooldown:
      default-days: 30
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 30
    schedule:
      interval: 'monthly'
    allow:
      - dependency-type: 'direct'
    versioning-strategy: increase
    commit-message:
      prefix: 'build(deps)'
      prefix-development: 'build(dev-deps)'
    labels: ['tech. enhancement']
    ignore:
      - dependency-name: 'rsuite'
    groups:
      non-major-dependencies:
        applies-to: version-updates
        dependency-type: production
        update-types: ['minor', 'patch']
      non-major-dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types: ['minor', 'patch']
    rebase-strategy: 'disabled'

  - package-ecosystem: 'npm'
    directory: '/e2e/release/sample'
    cooldown:
      default-days: 30
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 30
    schedule:
      interval: 'monthly'
    allow:
      - dependency-type: 'direct'
    versioning-strategy: increase
    commit-message:
      # `/e2e/release/sample` is only used for e2e release testing
      prefix: 'build(dev-deps)'
      prefix-development: 'build(dev-deps)'
    labels: ['tech. enhancement']
    rebase-strategy: 'disabled'
    groups:
      non-major-dependencies:
        applies-to: version-updates
        dependency-type: production
        update-types: ['minor', 'patch']
      non-major-dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types: ['minor', 'patch']
