version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build(deps)'
      prefix-development: 'build(dev-deps)'
  - package-ecosystem: 'npm'
    directory: '/e2e/release/sample'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build(deps)'
      prefix-development: 'build(dev-deps)'
