version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci(github)'
    labels: ['tech. enhancement']

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build(deps)'
      prefix-development: 'build(dev-deps)'
    labels: ['tech. enhancement']
    ignore:
      - dependency-name: 'rsuite'
    groups:
      non-major-dependencies:
        applies-to: version-updates
        dependency-type: production
        update-types: ['minor', 'patch']
      non-major-dev-dependencies:
        applies-to: version-updates
        dependency-type: development
        update-types: ['minor', 'patch']

  - package-ecosystem: 'npm'
    directory: '/e2e/release/sample'
    schedule:
      interval: 'weekly'
    commit-message:
      # `/e2e/release/sample` is only used for e2e release testing
      prefix: 'build(dev-deps)'
      prefix-development: 'build(dev-deps)'
    labels: ['tech. enhancement']
    groups:
      all-non-major-dependencies:
        update-types: ['minor', 'patch']
