version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'ci(github)'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: 'build(deps)'
      prefix-development: 'build(dev-deps)'

  - package-ecosystem: 'npm'
    directory: '/e2e/release/sample'
    schedule:
      interval: 'monthly'
    commit-message:
      # `/e2e/release/sample` is only used for e2e release testing
      prefix: 'build(dev-deps)'
      prefix-development: 'build(dev-deps)'
