language: 'fr'
early_access: true
chat:
  auto_reply: true

reviews:
  auto_review:
    enabled: true
    drafts: true
    base_branches:
      - 'main'
  collapse_walkthrough: false
  high_level_summary: false
  path_filters:
    - '!CHANGELOG.md'
    - '!**/package-lock.json'
    - '!**/yarn.lock'
  path_instructions:
    - path: '**/*'
      instructions: |
        - Keep your comments short.
        - Check for typos and bad English naming.
        - Proofread comments, documentation and code.
        - Avoid general concepts and focus on the code.
        - Suggest code changes with concrete code.
  poem: false
  request_changes_workflow: false
  review_status: false
