import ky from 'ky'
import { propEq } from 'ramda'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { AutoComplete as RsuiteAutoComplete } from 'rsuite'
import styled from 'styled-components'

import { Field } from '../elements/Field'
import { Label } from '../elements/Label'

import type { Option } from '../types'
import type { AutoCompleteProps as RsuiteAutoCompleteProps } from 'rsuite'
import type { Promisable } from 'type-fest'

export type AutoCompleteProps = Omit<
  RsuiteAutoCompleteProps,
  'as' | 'data' | 'id' | 'onChange' | 'onSelect' | 'value'
> & {
  isLabelHidden?: boolean
  isLight?: boolean
  label: string
  name: string
  onChange?: (nextValue: string | undefined) => Promisable<void>
  onQuery?: (nextQuery: string | undefined) => Promisable<void>
  options?: Option[]
  queryMap?: (record: Record<string, any>) => Option
  queryUrl?: string
}
export function AutoComplete({
  defaultValue,
  isLabelHidden,
  isLight = false,
  label,
  onChange,
  onQuery,
  options,
  queryMap,
  queryUrl,
  ...originalProps
}: AutoCompleteProps) {
  const prevDefaultValuePropRef = useRef<string | undefined>(defaultValue)

  const [controlledDefaultValue, setDefaultControlledValue] = useState<string | undefined>(defaultValue)
  const [autoGeneratedOptions, setAutoGeneratedOptions] = useState<Option[]>([])

  const controlledOptions = useMemo(() => options ?? autoGeneratedOptions, [autoGeneratedOptions, options])
  const controlledValueAsLabel = useMemo(() => {
    const foundOption = controlledOptions.find(propEq('value', controlledDefaultValue))

    return foundOption ? foundOption.label : undefined
  }, [controlledDefaultValue, controlledOptions])
  const key = useMemo(
    () => `${originalProps.name}-${JSON.stringify(controlledDefaultValue)}`,
    [controlledDefaultValue, originalProps.name]
  )

  const handleChange = useCallback(
    async (nextQuery: string) => {
      if (queryUrl && queryMap) {
        const url = queryUrl.replace('%s', nextQuery)
        const rawData: Record<string, any>[] = await ky.get(url).json()
        const nextData = rawData.map(queryMap)

        setAutoGeneratedOptions(nextData)
      }

      const normalizedNextQuery = nextQuery && nextQuery.trim().length ? nextQuery : undefined

      if (onChange && !normalizedNextQuery) {
        onChange(undefined)
      }

      if (onQuery) {
        onQuery(normalizedNextQuery)
      }
    },
    [onChange, onQuery, queryMap, queryUrl]
  )

  const handleSelect = useCallback(
    (nextValue: string) => {
      if (onChange) {
        onChange(nextValue)
      }

      setDefaultControlledValue(nextValue)
    },
    [onChange]
  )

  useEffect(() => {
    if (defaultValue === prevDefaultValuePropRef.current) {
      return
    }

    setDefaultControlledValue(defaultValue)
  }, [defaultValue])

  return (
    <Field>
      <Label htmlFor={originalProps.name} isHidden={isLabelHidden}>
        {label}
      </Label>

      <StyledAutoComplete
        key={key}
        $isLight={isLight}
        data={controlledOptions}
        defaultValue={controlledValueAsLabel}
        id={originalProps.name}
        onChange={handleChange}
        onSelect={handleSelect}
        {...originalProps}
      />
    </Field>
  )
}

const StyledAutoComplete = styled(RsuiteAutoComplete)<{
  $isLight: boolean
}>`
  font-size: 13px;

  > input {
    background-color: ${p => (p.$isLight ? p.theme.color.white : p.theme.color.gainsboro)};
    border: 0;
    font-size: 13px;
    width: 100%;
  }
`
