runs:
  using: 'composite'
  steps:
    - name: Enable Corepack and Yarn 4
      shell: bash
      run: |
        corepack enable
        corepack prepare yarn@4.9.0 --activate
        yarn --version

    - name: Configure Yarn cache to local folder
      shell: bash
      run: |
        yarn config set enableGlobalCache false
        yarn config set cacheFolder .yarn/cache
        yarn config get cacheFolder
        mkdir -p .yarn/cache

    - name: Setup
      uses: actions/setup-node@v5
      with:
        node-version: 24
        registry-url: https://registry.npmjs.org/
        cache: 'yarn'
        cache-dependency-path: |
          package.json
          yarn.lock

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable --inline-builds
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false'
        YARN_ENABLE_MIRROR: 'false'
        YARN_NM_MODE: 'hardlinks-local'
        HUSKY: '0'
