name: Deploy Temp

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
      - name: Deploy
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.2
        with:
          install_command: yarn install --frozen-lockfile
          build_command: yarn build:storybook
          path: storybook-static
          checkout: true
