name: E2E

on: push

jobs:
  # Normal E2E testing with Cypress
  test_e2e:
    name: E2E Test
    if: ${{ !startsWith(github.ref, 'refs/heads/ci-release-v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 104.0.2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 18
      - name: Install
        run: yarn
      - name: Test
        run: yarn test:e2e

  # Release build sanity check with Playwright
  test_e2e_release:
    name: Release E2E Test
    if: ${{ !startsWith(github.ref, 'refs/heads/ci-release-v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 104.0.2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 18
      - name: Install
        run: yarn
      - name: Serve Release Sample
        run: |
          yarn test:e2e:release:setup &
          bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 5; done'
      - name: Test
        run: yarn test:e2e:release

  # Storybook E2E Tests with test-storybook (Playwright under the hood)
  # https://storybook.js.org/docs/react/writing-tests/test-runner
  test_e2e_storybook:
    if: ${{ !startsWith(github.ref, 'refs/heads/ci-release-v') }}
    name: Storybook E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 18
      - name: Install
        run: |
          yarn
          npx playwright install firefox
      - name: Build Storybook
        run: yarn build:storybook
      - name: Serve Storybook
        run: |
          yarn serve &
          bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:6006)" != "200" ]]; do sleep 5; done'
      - name: Test
        run: yarn test:e2e:storybook
