name: E2E

on: push

jobs:
  # Normal E2E testing with Cypress
  test_e2e:
    name: E2E Test
    if: ${{ !startsWith('refs/heads/ci-release-v', github.ref) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 104.0.2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
      - name: Install
        run: yarn
      - name: Test
        run: yarn test:e2e
  test_e2e_in_paris:
    name: E2E Test
    if: ${{ !startsWith('refs/heads/ci-release-v', github.ref) }}
    strategy:
      matrix:
        timeZone: ['Europe/Paris']
        dst: ['', 'DST']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 104.0.2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
      - name: Install
        run: yarn
      - name: Set datetime & timezone
        run: |
          sudo timedatectl set-timezone '${{ matrix.timeZone }}'
          sudo date -s "$(date '+%Y')-${{ matrix.dst == 'DST' && '07' || '01' }}-01 00:00:00"
      - name: Log datetime & timezone
        run: timedatectl
      - name: Test
        run: yarn test:e2e

  # Release build sanity check with Playwright
  test_e2e_release:
    name: Release E2E Test
    if: ${{ !startsWith('refs/heads/ci-release-v', github.ref) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 104.0.2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
      - name: Install
        run: yarn
      - name: Serve Release Sample
        run: |
          yarn test:e2e:release:setup &
          bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 5; done'
      - name: Test
        run: yarn test:e2e:release

  # Storybook E2E Tests with test-storybook (Playwright under the hood)
  # https://storybook.js.org/docs/react/writing-tests/test-runner
  test_e2e_storybook:
    if: ${{ !startsWith('refs/heads/ci-release-v', github.ref) }}
    name: Storybook E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
      - name: Install
        run: yarn
      - name: Build Storybook
        run: yarn build:storybook
      - name: Serve Storybook
        run: |
          yarn serve &
          bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:6006)" != "200" ]]; do sleep 5; done'
      - name: Test
        run: yarn test:e2e:storybook
