name: E2E

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Normal E2E testing with Cypress
  test_e2e:
    name: E2E Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - name: Checkout
        if: ${{ !startsWith(github.head_ref, 'ci-release-v') }}
        uses: actions/checkout@v5
      - name: Setup
        if: ${{ !startsWith(github.head_ref, 'ci-release-v') }}
        uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: Install
        if: ${{ !startsWith(github.head_ref, 'ci-release-v') }}
        uses: ./.github/actions/install
      - name: Test
        if: ${{ !startsWith(github.head_ref, 'ci-release-v') }}
        uses: cypress-io/github-action@v6
        with:
          component: true
          config-file: config/cypress.config.ts
          install: false
          parallel: true
          record: true
          tag: components
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  # Release build sanity check with Cypress
  test_e2e_release:
    name: Release E2E Test
    if: ${{ !startsWith(github.head_ref, 'ci-release-v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup
        uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: Install
        uses: ./.github/actions/install
      - name: Serve Release Sample
        run: |
          yarn test:e2e:release:setup &
          bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 5; done'
      - name: Test
        uses: cypress-io/github-action@v6
        with:
          config-file: config/cypress.config.ts
          install: false
          parallel: false
          record: true
          tag: release
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
