name: Merge Release Pull Request

on:
  pull_request:
    branches:
      - 'ci-release-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.15.6
        with:
          token: ${{ secrets.GH_PAT }}
