name: Merge Dependabot Pull Request

on:
  pull_request:
    branches:
      - 'dependabot/*'
  workflow_run:
    workflows: [Check, E2E, Preview]
    types: [completed]

jobs:
  merge:
    name: Merge Dependabot Pull Request
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.15.6
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
