name: Merge Release Pull Request

on:
  pull_request:
    # That doesn't work for some reason.
    # branches:
    #   - 'ci-release-v[0-9]+.[0-9]+.[0-9]+'
    types: [edited, opened, synchronize]

jobs:
  merge:
    name: Merge Release Pull Request
    if: ${{ startsWith(github.head_ref, 'ci-release-v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.base.ref }}
      # - name: Merge pull request
      #   uses: pascalgn/automerge-action@v0.15.6
      #   # https://github.com/pascalgn/automerge-action#configuration
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      #     MERGE_LABELS: ''
      #     MERGE_METHOD: rebase
