name: Merge Release Pull Request

on:
  pull_request:
    branches:
      - 'ci-release-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  merge:
    name: Merge Release Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.15.6
        # https://github.com/pascalgn/automerge-action#configuration
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          MERGE_LABELS: ''
