name: Merge Dependabot Pull Request

on:
  workflow_run:
    # workflows: [Check, E2E, Preview]
    # Because of https://github.com/orgs/community/discussions/16059
    workflows: [E2E]
    types: [completed]
    branches:
      - 'dependabot/**'

jobs:
  merge:
    name: Merge Dependabot Pull Request
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.16.2
        # https://github.com/pascalgn/automerge-action#configuration
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          MERGE_LABELS: ''
          MERGE_METHOD: rebase
          UPDATE_RETRIES: 6
          UPDATE_RETRY_SLEEP: 10000
