name: Merge Dependabot Pull Request

on:
  workflow_run:
    # workflows: [Check, E2E, Preview]
    # Because of https://github.com/orgs/community/discussions/16059
    workflows: [E2E]
    types: [completed]

jobs:
  merge:
    name: Merge Dependabot Pull Request
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'dependabot/') && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.15.6
        # https://github.com/pascalgn/automerge-action#configuration
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          MERGE_LABELS: ''
          MERGE_METHOD: rebase
