name: Preview

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'ci-release-v') }}
    outputs:
      # https://www.chromatic.com/docs/github-actions#outputs
      storybookUrl: ${{ steps.publish.outputs.storybookUrl }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 20
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Publish
        id: publish
        uses: chromaui/action@v11
        with:
          buildScriptName: 'build:storybook'
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GH_PAT }}

  update_pull_request:
    name: Update Pull Request
    runs-on: ubuntu-latest
    needs: publish
    if: ${{ !startsWith(github.ref, 'refs/heads/ci-release-v') }}
    steps:
      - name: Update Pull Request Preview URL
        uses: ivangabriele/find-and-replace-pull-request-body@v1.1.5
        with:
          githubToken: ${{ secrets.GH_PAT }}
          find: AUTOFILLED_PREVIEW_URL
          isHtmlCommentTag: true
          replace: ${{ needs.publish.outputs.storybookUrl }}
