name: Preview

on: pull_request

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 18
      - name: Install
        run: yarn
      - name: Publish
        uses: chromaui/action@v1
        with:
          buildScriptName: preview
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GH_PAT }}
