name: Preview

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'ci-release-v') }}
    outputs:
      # https://www.chromatic.com/docs/github-actions#outputs
      storybookUrl: ${{ steps.publish.outputs.storybookUrl }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 100

      - name: Install
        uses: ./.github/actions/install

      - name: Publish
        id: publish
        uses: chromaui/action@v12
        with:
          buildScriptName: 'build:storybook'
          externals: src/assets/**
          onlyChanged: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          skip: 'dependabot/**'
          token: ${{ secrets.GH_TOKEN }}
          zip: true

  update_pull_request:
    name: Update Pull Request
    runs-on: ubuntu-latest
    needs: publish
    if: ${{ !startsWith(github.ref, 'refs/heads/ci-release-v') && github.event_name == 'pull_request'}}
    steps:
      - name: Update Pull Request Preview URL
        uses: ivangabriele/find-and-replace-pull-request-body@v1.1.5
        with:
          githubToken: ${{ secrets.GH_TOKEN }}
          find: AUTOFILLED_PREVIEW_URL
          isHtmlCommentTag: true
          replace: ${{ needs.publish.outputs.storybookUrl }}
