# Timezoned tests run daily on `main` branch
name: Timezone

on:
  schedule:
    # Daily, at 00:30 UTC
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  test_unit_in_paris:
    name: Unit Test
    if: ${{ !startsWith(github.ref, 'refs/heads/ci-release-v') }}
    strategy:
      matrix:
        timeZone: ['Europe/Paris']
        dst: ['', 'DST']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 20
      - name: Install
        run: yarn
      - name: Set datetime & timezone
        run: |
          sudo timedatectl set-timezone '${{ matrix.timeZone }}'
          sudo date -s "$(date '+%Y')-${{ matrix.dst == 'DST' && '07' || '01' }}-01 00:00:00"
      - name: Log datetime & timezone
        run: timedatectl
      - name: Test
        run: yarn test:unit

  test_e2e_in_paris:
    name: E2E Test
    if: ${{ !startsWith(github.ref, 'refs/heads/ci-release-v') }}
    strategy:
      matrix:
        timeZone: ['Europe/Paris']
        dst: ['', 'DST']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: 104.0.2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 20
      - name: Install
        run: yarn
      - name: Set datetime & timezone
        run: |
          sudo timedatectl set-timezone '${{ matrix.timeZone }}'
          sudo date -s "$(date '+%Y')-${{ matrix.dst == 'DST' && '07' || '01' }}-01 00:00:00"
      - name: Log datetime & timezone
        run: timedatectl
      - name: Test
        run: yarn test:e2e
